# Generated by Django 5.0.4 on 2024-04-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='rule',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
